"""
Fix file generator for AgentReady.

Generates tailored fix files based on scan results to help shop owners
improve their AI agent readiness score.
"""

import json
import re
from datetime import datetime, timezone

from db import get_scan


def _extract_payment_methods(checks: list[dict]) -> list[str]:
    """Extract detected payment methods from scan checks."""
    for check in checks:
        if check.get("name") == "Payment Methods":
            msg = check.get("message", "")
            # Parse "Found: visa, mastercard, paypal" style messages
            match = re.search(r"(?:Found|found)[:\s]+(.+?)\.?$", msg)
            if match:
                return [m.strip() for m in match.group(1).split(",")]
            # Parse "on page (visa, mastercard)" style
            match = re.search(r"\(([^)]+)\)", msg)
            if match:
                return [m.strip() for m in match.group(1).split(",")]
    return []


def _extract_shipping_keywords(checks: list[dict]) -> list[str]:
    """Extract detected shipping keywords from scan checks."""
    for check in checks:
        if check.get("name") == "Shipping Information":
            msg = check.get("message", "")
            match = re.search(r"Keywords?[:\s]+(.+?)\.?$", msg)
            if match:
                return [m.strip() for m in match.group(1).split(",")]
    return []


def _extract_return_keywords(checks: list[dict]) -> list[str]:
    """Extract detected return policy keywords from scan checks."""
    for check in checks:
        if check.get("name") == "Return Policy":
            msg = check.get("message", "")
            match = re.search(r"Keywords?[:\s]+(.+?)\.?$", msg)
            if match:
                return [m.strip() for m in match.group(1).split(",")]
    return []


def _check_status(checks: list[dict], name: str) -> str:
    """Get the status of a specific check by name."""
    for check in checks:
        if check.get("name") == name:
            return check.get("status", "fail")
    return "fail"


def _check_has_pass(checks: list[dict], name: str) -> bool:
    return _check_status(checks, name) == "pass"


def _get_failed_and_warned(checks: list[dict]) -> list[dict]:
    """Get all checks that failed or warned."""
    return [c for c in checks if c.get("status") in ("fail", "warn")]


def _detect_platform(domain: str, checks: list[dict]) -> str:
    """Try to detect the e-commerce platform from check messages."""
    all_messages = " ".join(c.get("message", "") for c in checks).lower()
    all_snippets = " ".join(c.get("code_snippet", "") or "" for c in checks).lower()
    combined = all_messages + " " + all_snippets

    if "shopify" in combined or "myshopify" in domain:
        return "shopify"
    if "woocommerce" in combined or "wp-content" in combined:
        return "woocommerce"
    if "magento" in combined:
        return "magento"
    if "prestashop" in combined:
        return "prestashop"
    return "custom"


def _generate_ai_txt(domain: str, checks: list[dict]) -> dict:
    """Generate a tailored ai.txt file."""
    payment_methods = _extract_payment_methods(checks)
    shipping_keywords = _extract_shipping_keywords(checks)
    return_keywords = _extract_return_keywords(checks)
    has_guest_checkout = _check_has_pass(checks, "Guest Checkout")

    lines = [
        f"# ai.txt for {domain}",
        f"# Generated by AgentReady - {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
        "",
        f"Name: {domain}",
        f"Homepage: https://{domain}",
        "",
        "# Allowed actions for AI agents",
        "Allow: /products",
        "Allow: /collections",
        "Allow: /categories",
        "Allow: /shop",
        "Allow: /catalog",
        "Allow: /search",
        "",
        "# Disallowed paths",
        "Disallow: /checkout",
        "Disallow: /account",
        "Disallow: /admin",
        "Disallow: /cart/update",
        "",
        "# Capabilities",
    ]

    if has_guest_checkout:
        lines.append("Capability: guest-checkout")
    else:
        lines.append("# Capability: guest-checkout  (not yet detected - enable to improve score)")

    if payment_methods:
        lines.append(f"Payment-Methods: {', '.join(payment_methods)}")
    else:
        lines.append("# Payment-Methods: VISA, Mastercard, PayPal  (add your accepted methods)")

    if shipping_keywords:
        lines.append(f"Shipping: Available ({', '.join(shipping_keywords[:3])})")
    else:
        lines.append("# Shipping: Available  (add shipping details)")

    if return_keywords:
        lines.append(f"Returns: Available ({', '.join(return_keywords[:3])})")
    else:
        lines.append("# Returns: Available  (add return policy details)")

    lines.extend([
        "",
        "# Contact",
        f"# Contact-Email: support@{domain}  (replace with your actual email)",
        f"# Contact-URL: https://{domain}/contact",
        "",
        "# Agent instructions",
        "Instructions: AI agents are welcome to browse product listings, compare prices,",
        "  and assist users with purchasing decisions. Please respect rate limits.",
        "  Do not scrape all pages in bulk. Use structured data when available.",
    ])

    return {
        "name": "ai.txt",
        "content": "\n".join(lines) + "\n",
        "description": "AI agent instructions file - place at your domain root (e.g., https://yourdomain.com/ai.txt)",
    }


def _generate_llms_txt(domain: str, checks: list[dict], report: dict) -> dict:
    """Generate a tailored llms.txt file."""
    grade = report.get("grade", "?")
    score = report.get("total_score", 0)
    categories = report.get("categories", {})
    payment_methods = _extract_payment_methods(checks)

    # Build description based on what was found
    desc_parts = [f"Online shop at {domain}"]
    if payment_methods:
        desc_parts.append(f"accepting {', '.join(payment_methods[:3])}")
    if _check_has_pass(checks, "Guest Checkout"):
        desc_parts.append("with guest checkout available")

    description = " ".join(desc_parts) + "."

    lines = [
        f"# {domain}",
        "",
        f"> {description}",
        "",
        "## About",
        "",
        f"This is the llms.txt file for {domain}, providing context for large language models.",
        "",
        "## Shop Information",
        "",
        f"- Website: https://{domain}",
        f"- AI Readiness Score: {score}/100 (Grade: {grade})",
    ]

    if payment_methods:
        lines.append(f"- Payment Methods: {', '.join(payment_methods)}")
    else:
        lines.append("- Payment Methods: [Add your payment methods here]")

    has_shipping = _check_status(checks, "Shipping Information") != "fail"
    has_returns = _check_status(checks, "Return Policy") != "fail"

    if has_shipping:
        lines.append("- Shipping: Available (see website for details)")
    else:
        lines.append("- Shipping: [Add shipping information]")

    if has_returns:
        lines.append("- Returns: Available (see website for details)")
    else:
        lines.append("- Returns: [Add return policy information]")

    lines.extend([
        "",
        "## Key Pages",
        "",
        f"- Homepage: https://{domain}",
        f"- Products: https://{domain}/products",
        f"- Collections: https://{domain}/collections",
        f"- Contact: https://{domain}/contact",
        "",
        "## For AI Agents",
        "",
        "This shop welcomes AI agents for product discovery and comparison.",
        "Structured data (JSON-LD) is available on product pages.",
        f"See https://{domain}/ai.txt for detailed agent instructions.",
        f"UCP endpoint: https://{domain}/.well-known/ucp",
    ])

    return {
        "name": "llms.txt",
        "content": "\n".join(lines) + "\n",
        "description": "LLM context file - place at your domain root or /.well-known/llms.txt",
    }


def _generate_robots_txt_additions(domain: str, checks: list[dict]) -> dict:
    """Generate robots.txt additions for AI bot policies."""
    ai_bots = [
        "GPTBot",
        "ChatGPT-User",
        "ClaudeBot",
        "Anthropic",
        "Google-Extended",
        "PerplexityBot",
        "CCBot",
    ]

    lines = [
        f"# AI Bot Rules for {domain}",
        f"# Generated by AgentReady - {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
        "# Add these lines to your existing robots.txt file",
        "",
    ]

    for bot in ai_bots:
        lines.extend([
            f"User-agent: {bot}",
            "Allow: /",
            "Allow: /products",
            "Allow: /collections",
            "Allow: /categories",
            "Allow: /shop",
            "Disallow: /checkout",
            "Disallow: /account",
            "Disallow: /admin",
            "Disallow: /cart",
            "",
        ])

    lines.extend([
        "# Sitemap (update with your actual sitemap URL)",
        f"Sitemap: https://{domain}/sitemap.xml",
    ])

    return {
        "name": "robots_txt_additions.txt",
        "content": "\n".join(lines) + "\n",
        "description": "Lines to add to your robots.txt - merge with your existing file",
    }


def _generate_ucp_json(domain: str, checks: list[dict]) -> dict:
    """Generate a UCP endpoint configuration."""
    payment_methods = _extract_payment_methods(checks)
    has_guest_checkout = _check_has_pass(checks, "Guest Checkout")
    has_shipping = _check_status(checks, "Shipping Information") != "fail"
    has_returns = _check_status(checks, "Return Policy") != "fail"

    ucp = {
        "version": "1.0",
        "business": {
            "name": domain,
            "url": f"https://{domain}",
            "type": "ecommerce",
            "contact": {
                "email": f"support@{domain}",
                "url": f"https://{domain}/contact",
            },
            "payment_methods": payment_methods if payment_methods else ["TODO: Add your payment methods"],
            "shipping": {
                "available": has_shipping,
                "details_url": f"https://{domain}/shipping",
            },
            "returns": {
                "available": has_returns,
                "details_url": f"https://{domain}/returns",
            },
        },
        "capabilities": {
            "guest_checkout": has_guest_checkout,
            "product_search": True,
            "product_browse": True,
            "price_comparison": True,
            "add_to_cart": True,
            "inventory_check": False,
            "order_tracking": False,
        },
        "agent_instructions": {
            "welcome": True,
            "rate_limit": "10 requests per minute",
            "preferred_format": "json-ld",
            "ai_txt_url": f"https://{domain}/ai.txt",
            "llms_txt_url": f"https://{domain}/llms.txt",
        },
    }

    content = json.dumps(ucp, indent=2)

    return {
        "name": "ucp.json",
        "content": content + "\n",
        "description": "UCP endpoint config - serve at /.well-known/ucp with Content-Type: application/json",
    }


def _generate_product_schema(domain: str, checks: list[dict]) -> dict:
    """Generate a Product schema.org JSON-LD template."""
    payment_methods = _extract_payment_methods(checks)
    has_shipping = _check_status(checks, "Shipping Information") != "fail"
    has_returns = _check_status(checks, "Return Policy") != "fail"

    schema = {
        "@context": "https://schema.org",
        "@type": "Product",
        "name": "[PRODUCT NAME]",
        "description": "[PRODUCT DESCRIPTION - be detailed for AI agents]",
        "image": [
            f"https://{domain}/images/[PRODUCT-IMAGE-1].jpg",
            f"https://{domain}/images/[PRODUCT-IMAGE-2].jpg",
        ],
        "sku": "[SKU-NUMBER]",
        "brand": {
            "@type": "Brand",
            "name": "[BRAND NAME]",
        },
        "offers": {
            "@type": "Offer",
            "url": f"https://{domain}/products/[PRODUCT-SLUG]",
            "priceCurrency": "USD",
            "price": "[PRICE]",
            "priceValidUntil": "[YYYY-MM-DD]",
            "availability": "https://schema.org/InStock",
            "itemCondition": "https://schema.org/NewCondition",
        },
        "aggregateRating": {
            "@type": "AggregateRating",
            "ratingValue": "[RATING e.g. 4.5]",
            "reviewCount": "[COUNT e.g. 42]",
        },
    }

    # Add payment methods if detected
    if payment_methods:
        schema["offers"]["acceptedPaymentMethod"] = [
            {"@type": "PaymentMethod", "name": pm} for pm in payment_methods
        ]
    else:
        schema["offers"]["acceptedPaymentMethod"] = [
            {"@type": "PaymentMethod", "name": "[PAYMENT METHOD e.g. VISA]"}
        ]

    # Add shipping details
    if has_shipping:
        schema["offers"]["shippingDetails"] = {
            "@type": "OfferShippingDetails",
            "shippingRate": {
                "@type": "MonetaryAmount",
                "value": "[SHIPPING COST or 0 for free]",
                "currency": "USD",
            },
            "deliveryTime": {
                "@type": "ShippingDeliveryTime",
                "handlingTime": {
                    "@type": "QuantitativeValue",
                    "minValue": 1,
                    "maxValue": 2,
                    "unitCode": "d",
                },
                "transitTime": {
                    "@type": "QuantitativeValue",
                    "minValue": 3,
                    "maxValue": 7,
                    "unitCode": "d",
                },
            },
            "shippingDestination": {
                "@type": "DefinedRegion",
                "addressCountry": "[COUNTRY CODE e.g. US]",
            },
        }
    else:
        schema["offers"]["shippingDetails"] = {
            "@type": "OfferShippingDetails",
            "shippingRate": {
                "@type": "MonetaryAmount",
                "value": "[SHIPPING COST]",
                "currency": "[CURRENCY]",
            },
            "deliveryTime": {
                "@type": "ShippingDeliveryTime",
                "handlingTime": {
                    "@type": "QuantitativeValue",
                    "minValue": "[MIN DAYS]",
                    "maxValue": "[MAX DAYS]",
                    "unitCode": "d",
                },
                "transitTime": {
                    "@type": "QuantitativeValue",
                    "minValue": "[MIN DAYS]",
                    "maxValue": "[MAX DAYS]",
                    "unitCode": "d",
                },
            },
        }

    # Add return policy
    if has_returns:
        schema["offers"]["hasMerchantReturnPolicy"] = {
            "@type": "MerchantReturnPolicy",
            "applicableCountry": "[COUNTRY CODE e.g. US]",
            "returnPolicyCategory": "https://schema.org/MerchantReturnFiniteReturnWindow",
            "merchantReturnDays": 30,
            "returnMethod": "https://schema.org/ReturnByMail",
            "returnFees": "https://schema.org/FreeReturn",
        }
    else:
        schema["offers"]["hasMerchantReturnPolicy"] = {
            "@type": "MerchantReturnPolicy",
            "applicableCountry": "[COUNTRY CODE]",
            "returnPolicyCategory": "https://schema.org/MerchantReturnFiniteReturnWindow",
            "merchantReturnDays": "[NUMBER OF DAYS]",
            "returnMethod": "https://schema.org/ReturnByMail",
            "returnFees": "[https://schema.org/FreeReturn or https://schema.org/ReturnShippingFees]",
        }

    content = json.dumps(schema, indent=2)

    return {
        "name": "schema_product.jsonld",
        "content": content + "\n",
        "description": "Product Schema.org JSON-LD template - embed in <script type=\"application/ld+json\"> on product pages",
    }


def _generate_organization_schema(domain: str, checks: list[dict]) -> dict:
    """Generate an Organization schema.org JSON-LD template."""
    payment_methods = _extract_payment_methods(checks)

    schema = {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": "[YOUR BUSINESS NAME]",
        "url": f"https://{domain}",
        "logo": f"https://{domain}/logo.png",
        "description": "[Brief description of your business for AI agents]",
        "contactPoint": {
            "@type": "ContactPoint",
            "telephone": "[+1-XXX-XXX-XXXX]",
            "email": f"[support@{domain}]",
            "contactType": "customer service",
            "availableLanguage": ["English"],
        },
        "address": {
            "@type": "PostalAddress",
            "streetAddress": "[STREET ADDRESS]",
            "addressLocality": "[CITY]",
            "addressRegion": "[STATE/REGION]",
            "postalCode": "[ZIP/POSTAL CODE]",
            "addressCountry": "[COUNTRY CODE e.g. US]",
        },
        "sameAs": [
            "[https://facebook.com/yourpage]",
            "[https://instagram.com/yourpage]",
            "[https://twitter.com/yourhandle]",
        ],
    }

    if payment_methods:
        schema["paymentAccepted"] = ", ".join(payment_methods)
    else:
        schema["paymentAccepted"] = "[VISA, Mastercard, PayPal, etc.]"

    content = json.dumps(schema, indent=2)

    return {
        "name": "schema_organization.jsonld",
        "content": content + "\n",
        "description": "Organization Schema.org JSON-LD - embed in <script type=\"application/ld+json\"> on all pages",
    }


def _generate_implementation_guide(
    domain: str, checks: list[dict], report: dict
) -> dict:
    """Generate a step-by-step implementation guide."""
    failed_warned = _get_failed_and_warned(checks)
    platform = _detect_platform(domain, checks)
    grade = report.get("grade", "?")
    score = report.get("total_score", 0)

    lines = [
        f"# AgentReady Implementation Guide for {domain}",
        "",
        f"**Current Score:** {score}/100 (Grade: {grade})",
        f"**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
        f"**Detected Platform:** {platform.title()}",
        "",
        "---",
        "",
        "## Quick Start",
        "",
        "This guide walks you through fixing each issue found in your scan.",
        "Files are included in this ZIP - deploy them to improve your score.",
        "",
        "### File Placement Summary",
        "",
        "| File | Location | Notes |",
        "|------|----------|-------|",
        f"| `ai.txt` | `https://{domain}/ai.txt` | Domain root |",
        f"| `llms.txt` | `https://{domain}/llms.txt` | Domain root or `/.well-known/llms.txt` |",
        f"| `robots.txt` additions | Merge into `https://{domain}/robots.txt` | Do NOT replace existing file |",
        f"| `ucp.json` | `https://{domain}/.well-known/ucp` | Serve as JSON |",
        "| `schema_product.jsonld` | Product page HTML `<head>` | One per product page |",
        "| `schema_organization.jsonld` | All pages HTML `<head>` | Site-wide |",
        "",
    ]

    # Platform-specific tips
    lines.extend([
        "---",
        "",
        "## Platform-Specific Setup",
        "",
    ])

    if platform == "shopify":
        lines.extend([
            "### Shopify",
            "",
            "- **ai.txt / llms.txt**: Upload via `Settings > Files`, then create URL redirects",
            "  from `/ai.txt` to the file URL, OR use a custom app/proxy.",
            "- **robots.txt**: Edit via `Settings > Custom robots.txt` (Shopify Plus) or use",
            "  `theme.liquid` with a conditional check.",
            "- **UCP endpoint**: Deploy as a Shopify Function or use a proxy app.",
            "  Alternatively, host on a subdomain or serverless function.",
            "- **Schema JSON-LD**: Edit `product.liquid` / `product.json` in your theme to add",
            "  the `<script type=\"application/ld+json\">` block.",
            "- **Organization Schema**: Add to `theme.liquid` in the `<head>` section.",
            "",
        ])
    elif platform == "woocommerce":
        lines.extend([
            "### WooCommerce",
            "",
            "- **ai.txt / llms.txt**: Upload to your WordPress root directory via FTP/SFTP,",
            "  or use a plugin to serve static files.",
            "- **robots.txt**: Edit via `Settings > Reading` or directly edit the `robots.txt`",
            "  in your WordPress root. You can also use Yoast SEO to manage it.",
            "- **UCP endpoint**: Add a custom REST API endpoint in your theme's `functions.php`",
            "  or create a simple plugin:",
            "  ```php",
            "  add_action('rest_api_init', function() {",
            "    register_rest_route('.well-known', '/ucp', [",
            "      'methods' => 'GET',",
            "      'callback' => function() { return json_decode(file_get_contents('ucp.json')); }",
            "    ]);",
            "  });",
            "  ```",
            "- **Schema JSON-LD**: Use a plugin like Yoast SEO, Rank Math, or add manually",
            "  to your theme's `single-product.php` template.",
            "- **Organization Schema**: Add to `header.php` or use your SEO plugin.",
            "",
        ])
    else:
        lines.extend([
            "### General / Custom Platform",
            "",
            "- **ai.txt / llms.txt**: Place in your web server's document root",
            "  (same directory as `index.html`).",
            "- **robots.txt**: Merge the provided additions into your existing `robots.txt`.",
            "- **UCP endpoint**: Configure your web server to serve `ucp.json` at",
            f"  `https://{domain}/.well-known/ucp` with `Content-Type: application/json`.",
            "  For Apache, add to `.htaccess`:",
            "  ```",
            "  RewriteRule ^.well-known/ucp$ ucp.json [L]",
            "  ```",
            "  For Nginx:",
            "  ```",
            "  location = /.well-known/ucp {",
            "    alias /path/to/ucp.json;",
            "    default_type application/json;",
            "  }",
            "  ```",
            "- **Schema JSON-LD**: Add `<script type=\"application/ld+json\">` blocks in your",
            "  page templates' `<head>` section.",
            "",
        ])

    # Issue-by-issue fixes
    lines.extend([
        "---",
        "",
        "## Issues Found & How to Fix Them",
        "",
    ])

    if not failed_warned:
        lines.extend([
            "No issues found! Your site has a perfect AI agent readiness score.",
            "",
        ])
    else:
        for i, check in enumerate(failed_warned, 1):
            status_label = "FAILED" if check["status"] == "fail" else "WARNING"
            status_icon = "X" if check["status"] == "fail" else "!"
            lines.extend([
                f"### {i}. [{status_icon}] {check['name']} ({check['category']}) - {status_label}",
                "",
                f"**Issue:** {check['message']}",
                "",
            ])

            if check.get("fix_suggestion"):
                lines.append(f"**Fix:** {check['fix_suggestion']}")
                lines.append("")

            # Add specific file reference
            name = check["name"]
            if name in ("ai.txt",):
                lines.append("**Deploy:** Use the included `ai.txt` file. Customize the commented lines.")
            elif name in ("llms.txt",):
                lines.append("**Deploy:** Use the included `llms.txt` file. Update placeholders.")
            elif name == "robots.txt AI Policies":
                lines.append("**Deploy:** Merge `robots_txt_additions.txt` into your existing `robots.txt`.")
            elif name == "UCP Endpoint":
                lines.append("**Deploy:** Serve the included `ucp.json` at `/.well-known/ucp`.")
            elif name in ("Product Schema", "Offer Schema"):
                lines.append("**Deploy:** Use `schema_product.jsonld` as a template. Fill in `[PLACEHOLDERS]` for each product.")
            elif name == "Organization Schema":
                lines.append("**Deploy:** Use `schema_organization.jsonld`. Fill in your business details.")
            elif name == "JSON-LD Structured Data":
                lines.append("**Deploy:** Add both `schema_product.jsonld` and `schema_organization.jsonld` to your pages.")
            elif name == "Guest Checkout":
                lines.extend([
                    "**Action:** Enable guest checkout in your e-commerce platform settings.",
                    "Make sure the option is clearly visible on the checkout page.",
                ])
            elif name == "Payment Methods":
                lines.extend([
                    "**Action:** List your payment methods visibly on your site AND in the",
                    "Organization schema (`paymentAccepted` field). See `schema_organization.jsonld`.",
                ])
            elif name == "Shipping Information":
                lines.extend([
                    "**Action:** Add shipping details to your product pages and include",
                    "`shippingDetails` in your Product schema. See `schema_product.jsonld`.",
                ])
            elif name == "Return Policy":
                lines.extend([
                    "**Action:** Add return policy information and include",
                    "`hasMerchantReturnPolicy` in your Offer schema. See `schema_product.jsonld`.",
                ])
            elif name == "Breadcrumb Schema":
                lines.append("**Action:** Add BreadcrumbList JSON-LD to your product and category pages.")
            elif name == "Aggregate Rating":
                lines.append("**Action:** Add AggregateRating to your Product schema if you have reviews.")
            elif name == "HTTPS + Security Headers":
                lines.append("**Action:** Enable HTTPS and add HSTS and CSP security headers.")
            elif name == "Contact / Organization Info":
                lines.append("**Deploy:** Use `schema_organization.jsonld` and fill in your contact details.")

            if check.get("code_snippet"):
                lines.extend([
                    "",
                    "**Example code:**",
                    "```",
                    check["code_snippet"],
                    "```",
                ])

            lines.extend(["", "---", ""])

    # Verification
    lines.extend([
        "",
        "## Verify Your Changes",
        "",
        "After deploying the fix files:",
        "",
        f"1. Visit https://agentready.org and scan `{domain}` again",
        "2. Check individual files are accessible:",
        f"   - `https://{domain}/ai.txt`",
        f"   - `https://{domain}/llms.txt`",
        f"   - `https://{domain}/robots.txt`",
        f"   - `https://{domain}/.well-known/ucp`",
        "3. Validate your JSON-LD at https://validator.schema.org/",
        "4. Test with Google's Rich Results Test",
        "",
        "---",
        "",
        "*Generated by AgentReady (https://agentready.org)*",
    ])

    return {
        "name": "implementation_guide.md",
        "content": "\n".join(lines) + "\n",
        "description": "Step-by-step implementation guide with platform-specific instructions",
    }


async def generate_fixes(scan_id: str) -> dict:
    """
    Generate tailored fix files based on a completed scan result.

    Args:
        scan_id: The scan ID to generate fixes for.

    Returns:
        Dict with files list, scan_id, and domain.

    Raises:
        ValueError: If scan not found or not completed.
    """
    scan = await get_scan(scan_id)
    if not scan:
        raise ValueError("Scan not found")

    if scan["status"] != "completed":
        raise ValueError(f"Scan is not completed (status: {scan['status']})")

    report = {}
    if scan["report_json"]:
        report = json.loads(scan["report_json"])

    domain = scan["domain"]
    checks = report.get("checks", [])

    files = [
        _generate_ai_txt(domain, checks),
        _generate_llms_txt(domain, checks, report),
        _generate_robots_txt_additions(domain, checks),
        _generate_ucp_json(domain, checks),
        _generate_product_schema(domain, checks),
        _generate_organization_schema(domain, checks),
        _generate_implementation_guide(domain, checks, report),
    ]

    return {
        "files": files,
        "scan_id": scan_id,
        "domain": domain,
    }
